# Generated by Django 6.0.1 on 2026-02-06 10:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('category', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('image', models.URLField(verbose_name='Rasm URL')),
                ('productId', models.FloatField(verbose_name='Mahsulot ID')),
                ('rate', models.FloatField(verbose_name='Reyting')),
                ('count', models.IntegerField(verbose_name='Soni')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='UserLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yoqtirgan',
                'verbose_name_plural': 'Yoqtirganlar',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='UserSavat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases_app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savat',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
